### ISSUE TITLE
`@verdaccio/local-storage` TypeScript types are gone from NPM

### ISSUE THREAD

**Issue by Leksat** [verdaccio/monorepo#659]
**Describe the bug**

After upgrading `@verdaccio/local-storage` from 10.3.1 to 10.3.2 I started to get TS errors like this one
```
error TS7016: Could not find a declaration file for module '@verdaccio/local-storage'
```

My code
```ts
import LocalDataBase from '@verdaccio/local-storage';
```

I have found that the removal of types happened here: https://github.com/verdaccio/monorepo/pull/653/files#diff-8ee64c91b245a2d7b3704bc22a5df031b567732609ac23b0de7ea3a8661bdc03L57-R56 But I don't get why.

`package.json` still states that [types are included](https://github.com/verdaccio/monorepo/blob/@verdaccio/local-storage@10.3.2/plugins/local-storage/package.json#L26), yet [they are gone](https://unpkg.com/@verdaccio/local-storage@10.3.2/lib/index.d.ts).

(I tried to add to the project `@verdaccio/types` and `@verdaccio/legacy-types` mentioned in the PR, but they don't have a declaration for `LocalDataBase`)

**Comment by juanpicado** [comment]
yes sorry, I what's the usage are you giving to the module?

**Comment by Leksat** [comment]
We use it to release packages to Git repositories: https://github.com/AmazeeLabs/silverback-mono/tree/development/packages/npm/verdaccio-git

**Comment by juanpicado** [comment]
I see, ok, 

What happened is I'm trying to reduce the multiple modules to maintain (migration from v5->v6-alpha, and merged this old types `@verdaccio/types` package with the new one `@verdaccio/types` in v6,

The legacy `@verdaccio/legacy-types` is just if someone need it, but I can improve that to keep supporting old types but with a different module. 

l'll try to restore the types soon, also will check where was `LocalDataBase` I don't remember right now.

I the meantime you can use `declare module "@verdaccio/local-storage"` to avoid TS ask for the modules.

**Comment by juanpicado** [comment]
Ok, now has types back, try again let me know if that helps
